spring:
  application:
    name: forma-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/forma?reWriteBatchedInserts=true&serverTimezone=Asia/Shanghai
    username: forma
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379

  flyway:
    enabled: true
    baseline-on-migrate: true

ip2region:
  v4:
    enabled: true
    db-path: classpath:ip2region/ip2region_v4.xdb
    searchers: 15
    cache-policy: VIndexCache  # NoCache, VIndexCache, BufferCache
  v6:
    enabled: true  # 如果没有 IPv6 数据文件，设为 false
    db-path: classpath:ip2region/ip2region_v6.xdb
    searchers: 15
    cache-policy: VIndexCache